on:
  pull_request_target:
    types: [ opened, reopened ]

jobs:
  push-to-head-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - run: |
          git config --global user.name "anthms"
          git config --global user.email "86444119+anthms@users.noreply.github.com"
          
          echo "#this is a comment" >> .github/workflows/change.yml
          git add .
          git commit -m "change from workflow run ${{ github.run_id }}"
          git push

  push-to-base-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
      - run: |
          git config --global user.name "anthms"
          git config --global user.email "86444119+anthms@users.noreply.github.com"
          
          echo "#this is a comment" >> .github/workflows/change.yml
          git add .
          git commit -m "change from workflow run ${{ github.run_id }}"
          git push

  push-to-head-w-token:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.SIA_PAT }}
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - run: |
          git config --global user.name "anthms"
          git config --global user.email "86444119+anthms@users.noreply.github.com"
          
          echo "#this is a comment" >> .github/workflows/change.yml
          git add .
          git commit -m "change from workflow run ${{ github.run_id }}"
          git push
