on:
  pull_request_target:
    types: [ opened, reopened ]

jobs:
  push-to-head-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.event.pull_request.head.ref }}
      - run: |
          git config --global user.name "anthms"
          git config --global user.email "86444119+anthms@users.noreply.github.com"
          
          echo "#this is a comment" >> .github/workflows/change.yml
          git add .
          git commit -m "change from workflow run ${{ github.run_id }}"
          git push origin
          
  push-to-default-ref:
    needs: push-to-head-branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
      - run: |
          git config --global user.name "anthms"
          git config --global user.email "86444119+anthms@users.noreply.github.com"

          echo "#this is a comment" >> .github/workflows/change.yml
          git add .
          git commit -m "change from workflow run ${{ github.run_id }}"
          git push origin
